apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
