apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
